### ISSUE TITLE
Widgets completion statu [meta]

### ISSUE THREAD

**Issue by tonifisler** [swiss/styleguide#2]
# *\* Structure Admin.ch **

H1: Links in sidebar nav
H2: Pages
List: sub-navigation in page
# Index
## README
- [ ] Coding Style  
- [ ] File organization  
- [ ] Conventions  
## ... (pages déjà présentes?)
# Base Layout
## Typography
- [x] Titles  
- [x] Paragraphs, strong and em and co.  
  - [ ] Page title (from content section) 
  - [x] Lists  
  ## Visual
- [x] Logo  
- [x] Colors  
- [x] Backgrounds  
- [x] Images  
  - [ ] Images & text (from content section) 
  - [x] Icons  
  ## Tables
- [x] Standard  
- [x] Striped  
- [x] ... (every section present atm)  
## Forms
- [x] Buttons  
- [x] Print button (from content section) 
- [ ] _link to download button (components)_ 
- [ ] _link to social buttons (components)_ 
- [ ] _link to search field and results (components)_ 
- [x] Radio buttons  
- [x] Checkboxes  
- [x] Dropdowns  
- [x] Forms  
- [ ] _link to Add to Cart form (components)_ 
# Navigation Components
## Header
- [x] Link to homepage (logo)  
- [x] Service-nav  
- [x] Lang nav  
- [x] Themes dropdown  
- [x] Search input  
- [x] Treecrumb  
## Hierarchy navigation
- [x] Global nav  
- [ ] Global nav MOBILE
- [x] Breadcrumb  
- [x] Back button  
- [x] Navigation lists  
- [x] Navigation Facettes  
## Content navigation
- [x] Pagination  
- [x] Anchors  
- [x] Top links (with variant)  
- [ ] Process nav  
- [x] Tabs  
## Footer
- [x] Sitemap & partners  
- [x] Social Media  
- [x] Footnote  
# Content Components
## Featuring widgets
- [ ] Carousel with text navigation  
- [ ] Featured news  
- [ ] Related themes  
- [ ] Carousel  
- [ ] Text-teaser
- [ ] Dossier-teaser
- [ ] Person-teaser
- [ ] Publications-Presentation
- [ ] News feed
- [ ] RSS Feed
## Widgets
- [x] Alert  
- [x] Emergency alert  
- [ ] Elements list module  
- [ ] Tabbed elements list module  
- [ ] Accordion  
- [ ] Contact box  
- [x] Timeline  
- [ ] Social buttons  
- [ ] Download list module  
## E-commerce
- [ ] Add to Cart form  
- [ ] Cart module  
## Search
- [ ] Search field  
- [ ] Search results module  
## Gallery
- [ ] Gallery  
- [ ] Single image  
- [ ] Lightbox
