### ISSUE TITLE
[meta] Pedro (admin) code review

### ISSUE THREAD

**Issue by gagarine** [swiss/styleguide#25]
This is a meta bug made with the code review we got by email. Don't hesitate to open specifics bugs if needed and referece theme back here.
- [#24] Usage of the CSS !important declaration is discouraged and should only be used in special cases as it breaks style overriding.
-  [#26] Avoid using vendor prefixes (.cortana-*) for CSS selector names.
### THE FOLLOWING POINTS ARE REGARDING THE THEME... This is not a priority.

§  js/ inside-navigation.js & js/sidenav.js:
- [ ] Refactor to jQuery plugins and provide data API (cf. Bootstrap JS plugins)
  
  §  js/template-helper.js:
- [ ] Do not perform specific DOM adaptation for styling: https://github.com/antistatique/Cortana-Swiss-Admin/blob/dev/assets/js/template-helper.js#L4

§  sass/layout.scss:
- [ ]    CSS rules for example code should be in a separate resource: https://github.com/antistatique/Cortana-Swiss-Admin/blob/dev/assets/sass/layout.scss#L63

§  sass/code.scss:
- [ ]   Highlight.js specific, should be externally provided or extracted to a separate resource: https://github.com/antistatique/Cortana-Swiss-Admin/blob/dev/assets/sass/code.scss#L64

§  sass/search.scss:
- [ ] Use font icons instead of image assets when possible (if needed, adapt HTML structure to provide the same visual result): https://github.com/antistatique/Cortana-Swiss-Admin/blob/dev/assets/sass/search.scss#L29

§  sass/text.scss:
- [ ]  Avoid scoping global CSS rules to specific contexts: https://github.com/antistatique/Cortana-Swiss-Admin/blob/dev/assets/sass/text.scss#L4

§  sass/variables.scss:
- [ ] Some color variables are not part of the WebGuidelines: https://github.com/antistatique/Cortana-Swiss-Admin/blob/dev/assets/sass/variables.scss#L2
- [ ] Some fonts are not part of the WebGuidelines: https://github.com/antistatique/Cortana-Swiss-Admin/blob/dev/assets/sass/variables.scss#L29
