### ISSUE TITLE
Print Styles 2.0

### ISSUE THREAD

**Issue by tonifisler** [swiss/styleguide#353]
This is a priority to fix. Print styles have to be reviewed and refactored.

- [x] Add option to display links in footnotes or not
- [x] Remove all navigations from print styles by default
- [x] Show content of all tabs (map for example)
- [x] Remove all Calls to Action.

### Round 2

- [ ] Fix IE9 Error (https://github.com/swiss/styleguide/issues/353#issuecomment-72666736)
- [ ] Fix error with News scroller (https://github.com/swiss/styleguide/issues/353#issuecomment-72665660)
- [ ] Remove back-links (https://github.com/swiss/styleguide/issues/353#issuecomment-72665660)
- [ ] Remove paginations (https://github.com/swiss/styleguide/issues/353#issuecomment-72665660)

~~The option to set all links as footnotes has to be further discussed (internally first). We don't know as of now whether it should be a feature of the styleguide or of the CMS you are using it in.~~

![print-css-bk](https://cloud.githubusercontent.com/assets/1708450/5972981/c27b1714-a862-11e4-97e2-0a9ca96a13c2.PNG)

**Comment by tonifisler** [comment]
https://dl.dropboxusercontent.com/u/2495529/EX1-print-css-aktuell-bk.pdf
https://dl.dropboxusercontent.com/u/2495529/Ex2-print-css-guidelines-2-5-0-commented.pdf

**Comment by Yago** [comment]
About "Add option to display links in footnotes or not", this a CMS or Browser feature. We can't only do that only with Javascript. So this feature will be implemented by the developers using the styleguide inside the CMS or technology that will be used in the final site.

About hiding some elements in print, you can simply used the `.hidden-print` as explained in the [Bootstrap documentation](http://getbootstrap.com/css/#responsive-utilities-print). We will update the examples with this class. But developers using the styleguide have to use it too.

**Comment by Yago** [comment]
@mbruellmann What do the "mit Kontextboxen drucken" settings ?

**Comment by mbruellmann** [comment]
@Yago We meen the stuff in the column on the right side of the page. See an example here of a page here. 
![page-with-contentbox](https://cloud.githubusercontent.com/assets/7466385/6018732/403cad46-ab99-11e4-98de-44ad47029786.PNG)

**Comment by Yago** [comment]
@mbruellmann By default we print all this content at the end of the document.

**Comment by mbruellmann** [comment]
Okay - thanks.

**Comment by tonifisler** [comment]
@Yago Should it work in the example pages? It currently does not.

![screen shot 2015-02-03 at 15 00 25](https://cloud.githubusercontent.com/assets/1708450/6021358/7fbf4e08-abb5-11e4-9726-2f5620bea164.png)

I should see the Links in the footer.

**Comment by Yago** [comment]
@tonifisler No because in our example page, there is no external link...

**Comment by tonifisler** [comment]
- Homepage with global nav, issue after the news scroller: ![screen shot 2015-02-03 at 15 59 17](https://cloud.githubusercontent.com/assets/1708450/6022519/ab4bfe1a-abbd-11e4-90a2-d599393307a5.png)

- We should add a `.hidden-print` class to the back-links. Useless when printing. ![screen shot 2015-02-03 at 16 01 49](https://cloud.githubusercontent.com/assets/1708450/6022573/0d5fc5f0-abbe-11e4-8635-31169849b727.png)

- Let's also hide this element (results page): ![screen shot 2015-02-03 at 16 03 48](https://cloud.githubusercontent.com/assets/1708450/6022610/4c8564ec-abbe-11e4-8872-bb914ac26638.png)

**Comment by tonifisler** [comment]
Big bug on IE9: 

![screen shot 2015-02-03 at 16 08 45](https://cloud.githubusercontent.com/assets/1708450/6022695/fe19af7e-abbe-11e4-93af-869f313a5069.png)


### How to reproduce

1. **ctrl+p to print** (will show you the js-manipulated DOM and the print window)
2. **cancel print window** 
3. **check "Links as footnotes"**

**Comment by tonifisler** [comment]
:shipit:
