### ISSUE TITLE
[meta] Visual differences between old and new styleguide

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#52]
M. Heilig
Treecrumb und Logo
- #59 Das Logo wird zu klein dargestellt.
- [x]   Der Rahmen für den Treecrumb ist zu hoch

Original:
![image](https://cloud.githubusercontent.com/assets/7510842/3012438/f6ab1ed2-df39-11e3-9155-76692ad79987.png)

New:
![image](https://cloud.githubusercontent.com/assets/7510842/3012485/781a2594-df3a-11e3-9c17-9d158b51de3d.png)
## Sprachnavigation
- [x]   Der Abstand zwischen den Sprachlinks (DE, FR, usw.) ist zu gross, was die Servicenavigation unnötig nach links verschiebt.

Original
![image](https://cloud.githubusercontent.com/assets/7510842/3012449/10529270-df3a-11e3-9dd0-74d9ea872e81.png)

New:
![image](https://cloud.githubusercontent.com/assets/7510842/3012499/b044fd68-df3a-11e3-95b0-280dee11563f.png)
## Globalnavigation
- #61 Titel sollen nicht verlinkt sein.
- #61 Zeilenabstand zwischen den Elementen ist zu klein.
- #60 Bei Klick neben das Flyout schliesst sich dieses nicht.

Original:
![image](https://cloud.githubusercontent.com/assets/7510842/3012460/2b6c0bd6-df3a-11e3-9471-7d7b2ea6de66.png)

New:
![image](https://cloud.githubusercontent.com/assets/7510842/3012473/4440cce6-df3a-11e3-8ced-584859880d50.png)
## Breadcrumb
- [x]   Zweite Zeile sollte nicht eingerückt sein
- [x]   Schrift zu klein für aktive Seite

Original
![image](https://cloud.githubusercontent.com/assets/7510842/3012503/c86e4624-df3a-11e3-8d31-be49599caf7b.png)

New
![image](https://cloud.githubusercontent.com/assets/7510842/3012509/d5567ea6-df3a-11e3-837c-e19faa7a0408.png)
## Navigation links
- [x]   Aktive Seite (you are here) sollte dunkler unterstrichen sein
- [x]   Die linke Navigationsspalte ist schmaler, d.h. es gibt einen grösseren Abstand zwischen der linken Navigation und dem Content.

Original:
![image](https://cloud.githubusercontent.com/assets/7510842/3012516/e7004cfe-df3a-11e3-92c4-28628ec7c31d.png)

New
![image](https://cloud.githubusercontent.com/assets/7510842/3012520/f32c3132-df3a-11e3-8beb-1a5ce9aa32fe.png)
## Typografie Fliesstext 1
- [x]   Die Schrift wird nicht sauber dargestellt (Beispiel: Buchstabe „T“  in Kleinschreibung.
- #62 Schriftgrösse „externer Link“ zu klein -> alle Schriftgrössen sind zu verifizieren

Original:
![image](https://cloud.githubusercontent.com/assets/7510842/3012529/047820f4-df3b-11e3-9b92-5b83ab8a74bf.png)

New:
![image](https://cloud.githubusercontent.com/assets/7510842/3012536/0fe36f48-df3b-11e3-9740-f80831963e97.png)
## Typografie Fliesstext 2
- #62 Grösse Teaser-Überschrift (zu gross).
- #62 Fliesstext läuft zu weit, müsste enger sein.

Original
![image](https://cloud.githubusercontent.com/assets/7510842/3012551/32247610-df3b-11e3-94df-d70cb3454210.png)

New:
![image](https://cloud.githubusercontent.com/assets/7510842/3012555/408e36aa-df3b-11e3-9e49-73cbf329c119.png)
## Brennpunkt-Element
- [x]   Titel aktives Element zu klein
- [x]   Text  im Tab zu klein, Tab-Höhe zu gering
- [x]   Teasertext-Bereich zu breit

Original
![image](https://cloud.githubusercontent.com/assets/7510842/3012564/538f70fc-df3b-11e3-83cf-6466e357d5ca.png)

New
![image](https://cloud.githubusercontent.com/assets/7510842/3012572/60e9499e-df3b-11e3-8c90-4f8db45fcd3a.png)
## Sitemap Footer
- #62 Überschrift zu gross
- [x]   Zeilenabstand zwischen den Links zu klein

Original
![image](https://cloud.githubusercontent.com/assets/7510842/3012573/69937768-df3b-11e3-918d-f2c23a477203.png)

New
![image](https://cloud.githubusercontent.com/assets/7510842/3012579/7bc44872-df3b-11e3-8c0e-a6ab161dbd2f.png)
